### ISSUE TITLE
from client, connect to `window.location.href`, rather than hard coded `localhost:8080`

### ISSUE THREAD

**Issue by kdbanman** [polyball/polyball#112]
EX: ryans VM setup has his VM IP and port 8080 in that field, but kirby's has `http://localhost:8080`

**Comment by ryant26** [comment]
I think this is going to be client side actually. Client Comms should try to connect to the URL  that was navigated to in the browser.

**Comment by kdbanman** [comment]
the more flexible solution is for the server to tell the client where to connect for a game.  you can imagine a situation where there are many game sessions, and going to `polyball.io` loads the game files, but your websocket connects to `polyball.io/game/44`. 

For capstone purposes, though, I think you're right.  All clients will just connect to the server root, and that can be grabbed on the client with javascript.
