### ISSUE TITLE
Server Comms is having trouble with a client adding to queue more than once

### ISSUE THREAD

**Issue by ryant26** [polyball/polyball#115]
Not quite sure what is going on here, but the server will crash when a client add's themselves to the queue more than once.

The crash is happening in server/Comms.js:128

My hunch:
1. Client adds themselves to queue
2. Server pulls them into players queue right away
3. Client  sends another request to add to queue with an empty spectator id since they are now a player

**Comment by ryant26** [comment]
Didn't realize Client.toConfig no longer returns the socket. When spectator is converted to player it is initialized without a socket. This is causing issues.

**Comment by kdbanman** [comment]
Sorry about changing that without making a post.  The Client was designed to be passed as -is between Spectator and Player, not as a config.  But I guess our construction pattern is to pass a config object, so I guess that was a silly design.

How did you end up dealing with this?  I think it'd be reasonable for the model.toSnapshot method could run through the Clients and remove the sockets before returning.  That way the sockets could stay in the config.

**Comment by kdbanman** [comment]
More generally, the model.toSnapshot could sweep through configs and remove non serializable parts.  That seems like a reasonable responsibility.

**Comment by ryant26** [comment]
> More generally, the model.toSnapshot could sweep through configs and remove non serializable parts.

I think this should be the solution as well. As of right now , I simply pull the socket out of the spectator and pass it along with my call to model.addPlayer.  I was just trying to get it working by any means when I did that.

**Comment by kdbanman** [comment]
> > More generally, the model.toSnapshot could sweep through configs and remove non serializable parts.
> I think this should be the solution as well. 

Ok.  Did you create an issue?  Or should I?
