### ISSUE TITLE
Client (composed with Player and Spectator) should have its own ID.

### ISSUE THREAD

**Issue by kdbanman** [polyball/polyball#140]
The client should have its own ID, because we need to consistently identify clients, even if they switch between Spectator and Player.

Is there any reason for Player and Spectator to have an ID field if this change is introduced?  Or should we just make the Client ID also identify its player or spectator?

**Comment by kdbanman** [comment]
This will require changes to:

- Client(config)
- Client#toConfig
- Player(config)
- Player#toConfig
- Spectator(config)
- Spectator#toConfig
- All Model#CRUD methods for both Players and Spectators  (including search - they can't use findByID(id) any more)
- Possibly Model player queue methods?


Can anybody think of anything else?

**Comment by ryant26** [comment]
This list looks complete to me.

**Comment by kdbanman** [comment]
Another:

- anywhere in the Synchronizer or submodules that does `snapshotPlayer.id` needs to be changed to `snapshotPlayer.clientConfig.id`

**Comment by kdbanman** [comment]
purging from backlog.  no time.  will revisit in the future if necessary.
