### ISSUE TITLE
Accumulate mouse movements in the HUD

### ISSUE THREAD

**Issue by ryant26** [polyball/polyball#145]
Client is sending too many mouse movements per aggregation cycle. The client should accumulate mouse movements over a configurable period of time and add the delta to the aggregated commands.

**Comment by ryant26** [comment]
Should deltas be accumulated (summed)? 


By that I mean, currently you throttle the mouse movements, so you could potentially have:

send delta (mousdelta=x) -> mousedelta = 2 -> mouseDelta = 1 -> send delta (mouse delta=1)

In a case like this the mousedelta =2 is dropped completely, only the mousedelta =1 would be sent.

I'm proposing you add them so that in this case: mousedelta=3 by the send send

What do you think @kdbanman

**Comment by kdbanman** [comment]
I don't think any mouse delta is ever dropped right now.

1. Every mouse delta is recorded in a `mousemove` listener and added to an accumulator.
2. At most every 30ms or so, that accumulator is sent to the synchronizer as a move command.
3. And every 60ms, the synchronizer sends each of those commands off to the server.

Or did I misunderstand?

**Comment by ryant26** [comment]
I must have been tired when I wrote this. You are absolutely right.
