### ISSUE TITLE
game does start rendering for all clients when transitioning from waiting for players to game running.

### ISSUE THREAD

**Issue by kdbanman** [polyball/polyball#149]
Tough to replicate this reliably.  Usually when I open 3 tabs and queue them all to play, the first tab I opened does not render the game.  That's the common case, but sometimes other clients seem to miss out on the rendering.

This also happens when clients are also open across separate machines, but I'm unsure of which clients are affected when.

Hypotheses:

- A critical round initialization event is being tossed from timeout or something.  Maybe if a tab is "behind" another tab, it doesn't always get socket events?
- Maybe the socket event makes it, but processing it fully relies on a`requestAnimationFrame`, which we *know* does not fire unless a tab is visible?

**Comment by ryant26** [comment]
The same happens when a tab begins rendering, but is then put in the background for too long. When you come back to it, it will no longer render
