### ISSUE TITLE
client memory leak

### ISSUE THREAD

**Issue by kdbanman** [polyball/polyball#200]
when these conditions are met, the client consumes memory at a linear rate until crash:

- tab is in focus

   (requestAnimationFrame callbacks are being called)

i can't actually find another cause.  it seems to leak faster when a round is in session.

**Comment by ryant26** [comment]
I noticed this too. I didn't realize others were experiencing this as well.

**Comment by kdbanman** [comment]
Just noticed it doesn't leak for spectators.

**Comment by kdbanman** [comment]
The objects that are being allocated are renderer objects.  In a 2 second span in a 7 player game:

![mem leak heap](http://i.imgur.com/q54maPy.png)

All of those objects touch `PIXI` if you dig into them.  Probably the biggest clue here is that there are 7 players and the number of objects allocated for all types are divisible by 7:

- 280 - 40x per player (20 per second)
- 560 - 80x per player (40 per second)
- 840 - 120x per player (60 per second)

**Comment by kdbanman** [comment]
Our main game loop runs on the physics ticker, which loops `requestAnimationFrame`.  That runs [60 times per second](http://jsfiddle.net/CtsY3/89/) on this machine, which also did the above heap snapshot, but that might not be as big of a clue because our game may not be running as fast.

**Comment by kdbanman** [comment]
The text is the culprit:

```javascript
        addText: function(text, style, offset, rotation) {
            var textObject = new Pixi.Text(text, style);
            textObject.anchor.set(0.5, 0.5);
            textObject.rotation = rotation;
            textObject.position = offset;

            textContainer.addChild(textObject);
        },
```

Commenting out calls to `addText` stops memory growth.  I'm passing this off to you @j-rewerts .
