### ISSUE TITLE
Paddle rotation wanders off center with many players:

### ISSUE THREAD

**Issue by kdbanman** [polyball/polyball#204]
![paddle rotation](http://i.imgur.com/ZQwouyt.png)

**Comment by ryant26** [comment]
be960686daabe85bc6cf9bc3d7a3d6a5cbb528e8

**Comment by kdbanman** [comment]
this is still happening.  sorry - forgot to comment when I dragged this back in.

**Comment by ryant26** [comment]
It's so weird. The fix worked for 8 players, but now 7 player (maybe less)
is effected. I do not know what is causing this

**Comment by ryant26** [comment]
@kdbanman I actually cannot reproduce this on my system. What # of players are you seeing this with?I tried with 3-9

**Comment by ryant26** [comment]
@kdbanman Ok I can reproduce this now

**Comment by kdbanman** [comment]
Are all players and their paddles created fresh each round?

Like, is there a chance that players are sticking with paddles from previous rounds, and their rotation is not being updated?
