### ISSUE TITLE
Black Hole is rendered off center when paired with King Midas

### ISSUE THREAD

**Issue by j-rewerts** [polyball/polyball#224]

**Comment by kdbanman** [comment]
pretty sure black hole ratio is calculated w.r.t. the renderer (WebGLRenderer) rendertarget.  Theres a _currentRenderTarget, a setRenderTarget...  see [here](https://github.com/pixijs/pixi.js/blob/039200b46d7840f065faa50739e4b98f69678db4/src/core/renderers/webgl/WebGLRenderer.js).

We should try calling renderer.setRenderTarget with the window bounds (or find some size/bounds setter that calls it further down).
