### ISSUE TITLE
Make spectator vote sequence diagram

### ISSUE THREAD

**Issue by kdbanman** [polyball/polyball#3]
Probably doesn't need to be a full on STSD - there is *no* need for clients to predict or smooth voting process.

1. Server sends all spectators packets saying "vote between these powerups"
2. Clients send vote packets.
3. At server, each client vote packet receipt triggers vote state update packets from server to all clients.
4. At client, each vote state update packet triggers rerender of the vote modal thingy.
5. After timeout, server closes vote
    1. Server stops listening to vote packets
    2. Server puts voted powerup into game state, which is distributed with the next snapshot

**Comment by ryant26** [comment]
Agree, I think this can simply be a sequence diagram.

**Comment by kdbanman** [comment]
moved to #14
